name: urbanpulse
description: Intelligent Urban Reporting System - UrbanPulse

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  provider: ^6.1.2

  # Image & video picking
  image_picker: ^1.1.2

  # Location / GPS
  geolocator: ^13.0.2
  geocoding: ^3.0.0

  # Local storage (persist reports between sessions)
  shared_preferences: ^2.3.2

  # UUID generation
  uuid: ^4.4.2

  # Permission handling
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
