name: urbanpulse
description: Intelligent Urban Reporting System - UrbanPulse

publish_to: 'none'

version: 1.0.2+2
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State management
  provider: ^6.1.2

  # Image & video picking
  image_picker: ^1.1.2

  # Location / GPS
  geolocator: ^13.0.2
  geocoding: ^3.0.0

  # Local storage (persist reports between sessions)
  shared_preferences: ^2.3.2

  # UUID generation
  uuid: ^4.4.2

  # Permission handling
  permission_handler: ^11.3.1
  flutter_svg: ^2.2.4
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  firebase_storage: ^13.3.0
  google_sign_in: ^6.2.2
  firebase_messaging: ^16.2.0
  cached_network_image: ^3.2.3

  # HTTP client for Cloudinary REST API uploads
  http: ^1.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
